version: "3.9"

services:
    # image project
    app28:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www

        networks:
            - socialmedia

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8028:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - socialmedia

    # db mysql
    db28:
        image: mysql:5.7.22
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: db_socialmedia
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_PASSWORD: secret
            MYSQL_USER: root
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3328:3306"
        networks:
            - socialmedia
# rede
networks:
    socialmedia:
        driver: bridge
